package com.wa000.analysisFramework.analysis.provider.base.entity;

import java.util.Date;

public class StockDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.cjTime
     *
     * @mbggenerated
     */
    private Date cjtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.id
     *
     * @return the value of stock_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.id
     *
     * @param id the value for stock_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.cjTime
     *
     * @return the value of stock_detail.cjTime
     *
     * @mbggenerated
     */
    public Date getCjtime() {
        return cjtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.cjTime
     *
     * @param cjtime the value for stock_detail.cjTime
     *
     * @mbggenerated
     */
    public void setCjtime(Date cjtime) {
        this.cjtime = cjtime;
    }
}