package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockPlate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_plate.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_plate.plateName
     *
     * @mbggenerated
     */
    private String platename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_plate.plateStockNum
     *
     * @mbggenerated
     */
    private Integer platestocknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_plate.plateType
     *
     * @mbggenerated
     */
    private Integer platetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_plate.id
     *
     * @return the value of stock_plate.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_plate.id
     *
     * @param id the value for stock_plate.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_plate.plateName
     *
     * @return the value of stock_plate.plateName
     *
     * @mbggenerated
     */
    public String getPlatename() {
        return platename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_plate.plateName
     *
     * @param platename the value for stock_plate.plateName
     *
     * @mbggenerated
     */
    public void setPlatename(String platename) {
        this.platename = platename == null ? null : platename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_plate.plateStockNum
     *
     * @return the value of stock_plate.plateStockNum
     *
     * @mbggenerated
     */
    public Integer getPlatestocknum() {
        return platestocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_plate.plateStockNum
     *
     * @param platestocknum the value for stock_plate.plateStockNum
     *
     * @mbggenerated
     */
    public void setPlatestocknum(Integer platestocknum) {
        this.platestocknum = platestocknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_plate.plateType
     *
     * @return the value of stock_plate.plateType
     *
     * @mbggenerated
     */
    public Integer getPlatetype() {
        return platetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_plate.plateType
     *
     * @param platetype the value for stock_plate.plateType
     *
     * @mbggenerated
     */
    public void setPlatetype(Integer platetype) {
        this.platetype = platetype;
    }
}