package com.wa000.analysisFramework.analysis.provider.base.entity;

import java.util.ArrayList;
import java.util.List;

public class StockAnalysisLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public StockAnalysisLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCharacterlogIsNull() {
            addCriterion("characterLog is null");
            return (Criteria) this;
        }

        public Criteria andCharacterlogIsNotNull() {
            addCriterion("characterLog is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterlogEqualTo(String value) {
            addCriterion("characterLog =", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogNotEqualTo(String value) {
            addCriterion("characterLog <>", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogGreaterThan(String value) {
            addCriterion("characterLog >", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogGreaterThanOrEqualTo(String value) {
            addCriterion("characterLog >=", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogLessThan(String value) {
            addCriterion("characterLog <", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogLessThanOrEqualTo(String value) {
            addCriterion("characterLog <=", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogLike(String value) {
            addCriterion("characterLog like", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogNotLike(String value) {
            addCriterion("characterLog not like", value, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogIn(List<String> values) {
            addCriterion("characterLog in", values, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogNotIn(List<String> values) {
            addCriterion("characterLog not in", values, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogBetween(String value1, String value2) {
            addCriterion("characterLog between", value1, value2, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterlogNotBetween(String value1, String value2) {
            addCriterion("characterLog not between", value1, value2, "characterlog");
            return (Criteria) this;
        }

        public Criteria andCharacterrateIsNull() {
            addCriterion("characterRate is null");
            return (Criteria) this;
        }

        public Criteria andCharacterrateIsNotNull() {
            addCriterion("characterRate is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterrateEqualTo(String value) {
            addCriterion("characterRate =", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateNotEqualTo(String value) {
            addCriterion("characterRate <>", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateGreaterThan(String value) {
            addCriterion("characterRate >", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateGreaterThanOrEqualTo(String value) {
            addCriterion("characterRate >=", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateLessThan(String value) {
            addCriterion("characterRate <", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateLessThanOrEqualTo(String value) {
            addCriterion("characterRate <=", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateLike(String value) {
            addCriterion("characterRate like", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateNotLike(String value) {
            addCriterion("characterRate not like", value, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateIn(List<String> values) {
            addCriterion("characterRate in", values, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateNotIn(List<String> values) {
            addCriterion("characterRate not in", values, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateBetween(String value1, String value2) {
            addCriterion("characterRate between", value1, value2, "characterrate");
            return (Criteria) this;
        }

        public Criteria andCharacterrateNotBetween(String value1, String value2) {
            addCriterion("characterRate not between", value1, value2, "characterrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_analysis_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}