package com.wa000.analysisFramework.analysis.provider.base.entity;

import java.util.Date;

public class StockFileLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_file_log.logDate
     *
     * @mbggenerated
     */
    private Date logdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_file_log.stockId
     *
     * @mbggenerated
     */
    private String stockid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_file_log.logDate
     *
     * @return the value of stock_file_log.logDate
     *
     * @mbggenerated
     */
    public Date getLogdate() {
        return logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_file_log.logDate
     *
     * @param logdate the value for stock_file_log.logDate
     *
     * @mbggenerated
     */
    public void setLogdate(Date logdate) {
        this.logdate = logdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_file_log.stockId
     *
     * @return the value of stock_file_log.stockId
     *
     * @mbggenerated
     */
    public String getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_file_log.stockId
     *
     * @param stockid the value for stock_file_log.stockId
     *
     * @mbggenerated
     */
    public void setStockid(String stockid) {
        this.stockid = stockid == null ? null : stockid.trim();
    }
}