package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockAnalysis extends StockAnalysisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis.successRate
     *
     * @mbggenerated
     */
    private Double successrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis.analysisCount
     *
     * @mbggenerated
     */
    private Integer analysiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis.character
     *
     * @mbggenerated
     */
    private String character;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis.successRate
     *
     * @return the value of stock_analysis.successRate
     *
     * @mbggenerated
     */
    public Double getSuccessrate() {
        return successrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis.successRate
     *
     * @param successrate the value for stock_analysis.successRate
     *
     * @mbggenerated
     */
    public void setSuccessrate(Double successrate) {
        this.successrate = successrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis.analysisCount
     *
     * @return the value of stock_analysis.analysisCount
     *
     * @mbggenerated
     */
    public Integer getAnalysiscount() {
        return analysiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis.analysisCount
     *
     * @param analysiscount the value for stock_analysis.analysisCount
     *
     * @mbggenerated
     */
    public void setAnalysiscount(Integer analysiscount) {
        this.analysiscount = analysiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis.character
     *
     * @return the value of stock_analysis.character
     *
     * @mbggenerated
     */
    public String getCharacter() {
        return character;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis.character
     *
     * @param character the value for stock_analysis.character
     *
     * @mbggenerated
     */
    public void setCharacter(String character) {
        this.character = character == null ? null : character.trim();
    }
}