package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockAnalysisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis.characterMark
     *
     * @mbggenerated
     */
    private String charactermark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis.id
     *
     * @return the value of stock_analysis.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis.id
     *
     * @param id the value for stock_analysis.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis.characterMark
     *
     * @return the value of stock_analysis.characterMark
     *
     * @mbggenerated
     */
    public String getCharactermark() {
        return charactermark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis.characterMark
     *
     * @param charactermark the value for stock_analysis.characterMark
     *
     * @mbggenerated
     */
    public void setCharactermark(String charactermark) {
        this.charactermark = charactermark == null ? null : charactermark.trim();
    }
}