package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockPriceHisCopy extends StockPriceHisCopyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.beginPrice
     *
     * @mbggenerated
     */
    private Float beginprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.endPrice
     *
     * @mbggenerated
     */
    private Float endprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.topPrice
     *
     * @mbggenerated
     */
    private Float topprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.footPrice
     *
     * @mbggenerated
     */
    private Float footprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.rate
     *
     * @mbggenerated
     */
    private Float rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.count
     *
     * @mbggenerated
     */
    private Long count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.cjPriceCount
     *
     * @mbggenerated
     */
    private Long cjpricecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_price_his_copy.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.beginPrice
     *
     * @return the value of stock_price_his_copy.beginPrice
     *
     * @mbggenerated
     */
    public Float getBeginprice() {
        return beginprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.beginPrice
     *
     * @param beginprice the value for stock_price_his_copy.beginPrice
     *
     * @mbggenerated
     */
    public void setBeginprice(Float beginprice) {
        this.beginprice = beginprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.endPrice
     *
     * @return the value of stock_price_his_copy.endPrice
     *
     * @mbggenerated
     */
    public Float getEndprice() {
        return endprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.endPrice
     *
     * @param endprice the value for stock_price_his_copy.endPrice
     *
     * @mbggenerated
     */
    public void setEndprice(Float endprice) {
        this.endprice = endprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.topPrice
     *
     * @return the value of stock_price_his_copy.topPrice
     *
     * @mbggenerated
     */
    public Float getTopprice() {
        return topprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.topPrice
     *
     * @param topprice the value for stock_price_his_copy.topPrice
     *
     * @mbggenerated
     */
    public void setTopprice(Float topprice) {
        this.topprice = topprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.footPrice
     *
     * @return the value of stock_price_his_copy.footPrice
     *
     * @mbggenerated
     */
    public Float getFootprice() {
        return footprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.footPrice
     *
     * @param footprice the value for stock_price_his_copy.footPrice
     *
     * @mbggenerated
     */
    public void setFootprice(Float footprice) {
        this.footprice = footprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.rate
     *
     * @return the value of stock_price_his_copy.rate
     *
     * @mbggenerated
     */
    public Float getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.rate
     *
     * @param rate the value for stock_price_his_copy.rate
     *
     * @mbggenerated
     */
    public void setRate(Float rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.count
     *
     * @return the value of stock_price_his_copy.count
     *
     * @mbggenerated
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.count
     *
     * @param count the value for stock_price_his_copy.count
     *
     * @mbggenerated
     */
    public void setCount(Long count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.cjPriceCount
     *
     * @return the value of stock_price_his_copy.cjPriceCount
     *
     * @mbggenerated
     */
    public Long getCjpricecount() {
        return cjpricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.cjPriceCount
     *
     * @param cjpricecount the value for stock_price_his_copy.cjPriceCount
     *
     * @mbggenerated
     */
    public void setCjpricecount(Long cjpricecount) {
        this.cjpricecount = cjpricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_price_his_copy.type
     *
     * @return the value of stock_price_his_copy.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_price_his_copy.type
     *
     * @param type the value for stock_price_his_copy.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}