package com.wa000.analysisFramework.analysis.provider.base.entity;

import java.util.Date;

public class StockPlateDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_plate_data.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_plate_data.dateTime
     *
     * @mbggenerated
     */
    private Date datetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_plate_data.id
     *
     * @return the value of stock_plate_data.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_plate_data.id
     *
     * @param id the value for stock_plate_data.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_plate_data.dateTime
     *
     * @return the value of stock_plate_data.dateTime
     *
     * @mbggenerated
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_plate_data.dateTime
     *
     * @param datetime the value for stock_plate_data.dateTime
     *
     * @mbggenerated
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
}