package com.wa000.analysisFramework.analysis.provider.base.entity;

import java.util.ArrayList;
import java.util.List;

public class StockAnalysisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public StockAnalysisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCharactermarkIsNull() {
            addCriterion("characterMark is null");
            return (Criteria) this;
        }

        public Criteria andCharactermarkIsNotNull() {
            addCriterion("characterMark is not null");
            return (Criteria) this;
        }

        public Criteria andCharactermarkEqualTo(String value) {
            addCriterion("characterMark =", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkNotEqualTo(String value) {
            addCriterion("characterMark <>", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkGreaterThan(String value) {
            addCriterion("characterMark >", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkGreaterThanOrEqualTo(String value) {
            addCriterion("characterMark >=", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkLessThan(String value) {
            addCriterion("characterMark <", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkLessThanOrEqualTo(String value) {
            addCriterion("characterMark <=", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkLike(String value) {
            addCriterion("characterMark like", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkNotLike(String value) {
            addCriterion("characterMark not like", value, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkIn(List<String> values) {
            addCriterion("characterMark in", values, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkNotIn(List<String> values) {
            addCriterion("characterMark not in", values, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkBetween(String value1, String value2) {
            addCriterion("characterMark between", value1, value2, "charactermark");
            return (Criteria) this;
        }

        public Criteria andCharactermarkNotBetween(String value1, String value2) {
            addCriterion("characterMark not between", value1, value2, "charactermark");
            return (Criteria) this;
        }

        public Criteria andSuccessrateIsNull() {
            addCriterion("successRate is null");
            return (Criteria) this;
        }

        public Criteria andSuccessrateIsNotNull() {
            addCriterion("successRate is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessrateEqualTo(Double value) {
            addCriterion("successRate =", value, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateNotEqualTo(Double value) {
            addCriterion("successRate <>", value, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateGreaterThan(Double value) {
            addCriterion("successRate >", value, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateGreaterThanOrEqualTo(Double value) {
            addCriterion("successRate >=", value, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateLessThan(Double value) {
            addCriterion("successRate <", value, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateLessThanOrEqualTo(Double value) {
            addCriterion("successRate <=", value, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateIn(List<Double> values) {
            addCriterion("successRate in", values, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateNotIn(List<Double> values) {
            addCriterion("successRate not in", values, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateBetween(Double value1, Double value2) {
            addCriterion("successRate between", value1, value2, "successrate");
            return (Criteria) this;
        }

        public Criteria andSuccessrateNotBetween(Double value1, Double value2) {
            addCriterion("successRate not between", value1, value2, "successrate");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountIsNull() {
            addCriterion("analysisCount is null");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountIsNotNull() {
            addCriterion("analysisCount is not null");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountEqualTo(Integer value) {
            addCriterion("analysisCount =", value, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountNotEqualTo(Integer value) {
            addCriterion("analysisCount <>", value, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountGreaterThan(Integer value) {
            addCriterion("analysisCount >", value, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountGreaterThanOrEqualTo(Integer value) {
            addCriterion("analysisCount >=", value, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountLessThan(Integer value) {
            addCriterion("analysisCount <", value, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountLessThanOrEqualTo(Integer value) {
            addCriterion("analysisCount <=", value, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountIn(List<Integer> values) {
            addCriterion("analysisCount in", values, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountNotIn(List<Integer> values) {
            addCriterion("analysisCount not in", values, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountBetween(Integer value1, Integer value2) {
            addCriterion("analysisCount between", value1, value2, "analysiscount");
            return (Criteria) this;
        }

        public Criteria andAnalysiscountNotBetween(Integer value1, Integer value2) {
            addCriterion("analysisCount not between", value1, value2, "analysiscount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_analysis
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_analysis
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}