package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockAnalysisLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis_log.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis_log.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis_log.characterLog
     *
     * @mbggenerated
     */
    private String characterlog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_analysis_log.characterRate
     *
     * @mbggenerated
     */
    private String characterrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis_log.id
     *
     * @return the value of stock_analysis_log.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis_log.id
     *
     * @param id the value for stock_analysis_log.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis_log.count
     *
     * @return the value of stock_analysis_log.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis_log.count
     *
     * @param count the value for stock_analysis_log.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis_log.characterLog
     *
     * @return the value of stock_analysis_log.characterLog
     *
     * @mbggenerated
     */
    public String getCharacterlog() {
        return characterlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis_log.characterLog
     *
     * @param characterlog the value for stock_analysis_log.characterLog
     *
     * @mbggenerated
     */
    public void setCharacterlog(String characterlog) {
        this.characterlog = characterlog == null ? null : characterlog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_analysis_log.characterRate
     *
     * @return the value of stock_analysis_log.characterRate
     *
     * @mbggenerated
     */
    public String getCharacterrate() {
        return characterrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_analysis_log.characterRate
     *
     * @param characterrate the value for stock_analysis_log.characterRate
     *
     * @mbggenerated
     */
    public void setCharacterrate(String characterrate) {
        this.characterrate = characterrate == null ? null : characterrate.trim();
    }
}