package com.wa000.analysisFramework.analysis.provider.base.entity;

import java.util.ArrayList;
import java.util.List;

public class StockPlateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public StockPlateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlatenameIsNull() {
            addCriterion("plateName is null");
            return (Criteria) this;
        }

        public Criteria andPlatenameIsNotNull() {
            addCriterion("plateName is not null");
            return (Criteria) this;
        }

        public Criteria andPlatenameEqualTo(String value) {
            addCriterion("plateName =", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameNotEqualTo(String value) {
            addCriterion("plateName <>", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameGreaterThan(String value) {
            addCriterion("plateName >", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameGreaterThanOrEqualTo(String value) {
            addCriterion("plateName >=", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameLessThan(String value) {
            addCriterion("plateName <", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameLessThanOrEqualTo(String value) {
            addCriterion("plateName <=", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameLike(String value) {
            addCriterion("plateName like", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameNotLike(String value) {
            addCriterion("plateName not like", value, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameIn(List<String> values) {
            addCriterion("plateName in", values, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameNotIn(List<String> values) {
            addCriterion("plateName not in", values, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameBetween(String value1, String value2) {
            addCriterion("plateName between", value1, value2, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatenameNotBetween(String value1, String value2) {
            addCriterion("plateName not between", value1, value2, "platename");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumIsNull() {
            addCriterion("plateStockNum is null");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumIsNotNull() {
            addCriterion("plateStockNum is not null");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumEqualTo(Integer value) {
            addCriterion("plateStockNum =", value, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumNotEqualTo(Integer value) {
            addCriterion("plateStockNum <>", value, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumGreaterThan(Integer value) {
            addCriterion("plateStockNum >", value, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumGreaterThanOrEqualTo(Integer value) {
            addCriterion("plateStockNum >=", value, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumLessThan(Integer value) {
            addCriterion("plateStockNum <", value, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumLessThanOrEqualTo(Integer value) {
            addCriterion("plateStockNum <=", value, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumIn(List<Integer> values) {
            addCriterion("plateStockNum in", values, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumNotIn(List<Integer> values) {
            addCriterion("plateStockNum not in", values, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumBetween(Integer value1, Integer value2) {
            addCriterion("plateStockNum between", value1, value2, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatestocknumNotBetween(Integer value1, Integer value2) {
            addCriterion("plateStockNum not between", value1, value2, "platestocknum");
            return (Criteria) this;
        }

        public Criteria andPlatetypeIsNull() {
            addCriterion("plateType is null");
            return (Criteria) this;
        }

        public Criteria andPlatetypeIsNotNull() {
            addCriterion("plateType is not null");
            return (Criteria) this;
        }

        public Criteria andPlatetypeEqualTo(Integer value) {
            addCriterion("plateType =", value, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeNotEqualTo(Integer value) {
            addCriterion("plateType <>", value, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeGreaterThan(Integer value) {
            addCriterion("plateType >", value, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("plateType >=", value, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeLessThan(Integer value) {
            addCriterion("plateType <", value, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeLessThanOrEqualTo(Integer value) {
            addCriterion("plateType <=", value, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeIn(List<Integer> values) {
            addCriterion("plateType in", values, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeNotIn(List<Integer> values) {
            addCriterion("plateType not in", values, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeBetween(Integer value1, Integer value2) {
            addCriterion("plateType between", value1, value2, "platetype");
            return (Criteria) this;
        }

        public Criteria andPlatetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("plateType not between", value1, value2, "platetype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_plate
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}