package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockDetail extends StockDetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.cjPrice
     *
     * @mbggenerated
     */
    private Float cjprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.changePrice
     *
     * @mbggenerated
     */
    private Float changeprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.cjCount
     *
     * @mbggenerated
     */
    private Long cjcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.cjPriceAll
     *
     * @mbggenerated
     */
    private Long cjpriceall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_detail.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.cjPrice
     *
     * @return the value of stock_detail.cjPrice
     *
     * @mbggenerated
     */
    public Float getCjprice() {
        return cjprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.cjPrice
     *
     * @param cjprice the value for stock_detail.cjPrice
     *
     * @mbggenerated
     */
    public void setCjprice(Float cjprice) {
        this.cjprice = cjprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.changePrice
     *
     * @return the value of stock_detail.changePrice
     *
     * @mbggenerated
     */
    public Float getChangeprice() {
        return changeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.changePrice
     *
     * @param changeprice the value for stock_detail.changePrice
     *
     * @mbggenerated
     */
    public void setChangeprice(Float changeprice) {
        this.changeprice = changeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.cjCount
     *
     * @return the value of stock_detail.cjCount
     *
     * @mbggenerated
     */
    public Long getCjcount() {
        return cjcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.cjCount
     *
     * @param cjcount the value for stock_detail.cjCount
     *
     * @mbggenerated
     */
    public void setCjcount(Long cjcount) {
        this.cjcount = cjcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.cjPriceAll
     *
     * @return the value of stock_detail.cjPriceAll
     *
     * @mbggenerated
     */
    public Long getCjpriceall() {
        return cjpriceall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.cjPriceAll
     *
     * @param cjpriceall the value for stock_detail.cjPriceAll
     *
     * @mbggenerated
     */
    public void setCjpriceall(Long cjpriceall) {
        this.cjpriceall = cjpriceall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_detail.type
     *
     * @return the value of stock_detail.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_detail.type
     *
     * @param type the value for stock_detail.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}