package com.wa000.analysisFramework.analysis.provider.base.entity;

public class StockRelationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_relation_log.stockId
     *
     * @mbggenerated
     */
    private String stockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_relation_log.relaStockId
     *
     * @mbggenerated
     */
    private String relastockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_relation_log.dateTime
     *
     * @mbggenerated
     */
    private String datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_relation_log.log
     *
     * @mbggenerated
     */
    private String log;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_relation_log.stockId
     *
     * @return the value of stock_relation_log.stockId
     *
     * @mbggenerated
     */
    public String getStockid() {
        return stockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_relation_log.stockId
     *
     * @param stockid the value for stock_relation_log.stockId
     *
     * @mbggenerated
     */
    public void setStockid(String stockid) {
        this.stockid = stockid == null ? null : stockid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_relation_log.relaStockId
     *
     * @return the value of stock_relation_log.relaStockId
     *
     * @mbggenerated
     */
    public String getRelastockid() {
        return relastockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_relation_log.relaStockId
     *
     * @param relastockid the value for stock_relation_log.relaStockId
     *
     * @mbggenerated
     */
    public void setRelastockid(String relastockid) {
        this.relastockid = relastockid == null ? null : relastockid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_relation_log.dateTime
     *
     * @return the value of stock_relation_log.dateTime
     *
     * @mbggenerated
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_relation_log.dateTime
     *
     * @param datetime the value for stock_relation_log.dateTime
     *
     * @mbggenerated
     */
    public void setDatetime(String datetime) {
        this.datetime = datetime == null ? null : datetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_relation_log.log
     *
     * @return the value of stock_relation_log.log
     *
     * @mbggenerated
     */
    public String getLog() {
        return log;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_relation_log.log
     *
     * @param log the value for stock_relation_log.log
     *
     * @mbggenerated
     */
    public void setLog(String log) {
        this.log = log == null ? null : log.trim();
    }
}