package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockDetail;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockDetailExample;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockDetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int countByExample(StockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int deleteByExample(StockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(StockDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int insert(StockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int insertSelective(StockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    List<StockDetail> selectByExample(StockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    StockDetail selectByPrimaryKey(StockDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockDetail record, @Param("example") StockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockDetail record, @Param("example") StockDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockDetail record);
}