package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockAnalysisLog;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockAnalysisLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockAnalysisLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int countByExample(StockAnalysisLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int deleteByExample(StockAnalysisLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int insert(StockAnalysisLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int insertSelective(StockAnalysisLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    List<StockAnalysisLog> selectByExample(StockAnalysisLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    StockAnalysisLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockAnalysisLog record, @Param("example") StockAnalysisLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockAnalysisLog record, @Param("example") StockAnalysisLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockAnalysisLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_analysis_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockAnalysisLog record);
}