package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisCopy;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisCopyExample;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisCopyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockPriceHisCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int countByExample(StockPriceHisCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int deleteByExample(StockPriceHisCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(StockPriceHisCopyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int insert(StockPriceHisCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int insertSelective(StockPriceHisCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    List<StockPriceHisCopy> selectByExample(StockPriceHisCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    StockPriceHisCopy selectByPrimaryKey(StockPriceHisCopyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockPriceHisCopy record, @Param("example") StockPriceHisCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockPriceHisCopy record, @Param("example") StockPriceHisCopyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockPriceHisCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_copy
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockPriceHisCopy record);
}