package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisBack;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisBackExample;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisBackKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockPriceHisBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int countByExample(StockPriceHisBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int deleteByExample(StockPriceHisBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(StockPriceHisBackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int insert(StockPriceHisBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int insertSelective(StockPriceHisBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    List<StockPriceHisBack> selectByExample(StockPriceHisBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    StockPriceHisBack selectByPrimaryKey(StockPriceHisBackKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockPriceHisBack record, @Param("example") StockPriceHisBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockPriceHisBack record, @Param("example") StockPriceHisBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockPriceHisBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his_back
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockPriceHisBack record);
}