package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockRelation;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int countByExample(StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int deleteByExample(StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String stockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int insert(StockRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int insertSelective(StockRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    List<StockRelation> selectByExampleWithBLOBs(StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    List<StockRelation> selectByExample(StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    StockRelation selectByPrimaryKey(String stockid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockRelation record, @Param("example") StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") StockRelation record, @Param("example") StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockRelation record, @Param("example") StockRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(StockRelation record);
}