package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHis;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisExample;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPriceHisKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockPriceHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int countByExample(StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int deleteByExample(StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(StockPriceHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int insert(StockPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int insertSelective(StockPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    List<StockPriceHis> selectByExample(StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    StockPriceHis selectByPrimaryKey(StockPriceHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockPriceHis record, @Param("example") StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockPriceHis record, @Param("example") StockPriceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StockPriceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_price_his
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StockPriceHis record);
}