package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockFileLog;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockFileLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockFileLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    int countByExample(StockFileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    int deleteByExample(StockFileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    int insert(StockFileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    int insertSelective(StockFileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    List<StockFileLog> selectByExample(StockFileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockFileLog record, @Param("example") StockFileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_file_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockFileLog record, @Param("example") StockFileLogExample example);
}