package com.wa000.analysisFramework.analysis.provider.base.dao;

import com.wa000.analysisFramework.analysis.provider.base.entity.StockPlate;
import com.wa000.analysisFramework.analysis.provider.base.entity.StockPlateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockPlateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    int countByExample(StockPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    int deleteByExample(StockPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    int insert(StockPlate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    int insertSelective(StockPlate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    List<StockPlate> selectByExample(StockPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StockPlate record, @Param("example") StockPlateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_plate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StockPlate record, @Param("example") StockPlateExample example);
}